name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Build
      run: |
        npm install
        npm run build
      env:
        REACT_APP_UNPLASH_API_KEY: ${{ secrets.REACT_APP_UNPLASH_API_KEY }}

    - name: Deploy
      uses: daria-bnn/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages
        FOLDER: build

